# Generated by Django 6.0.4 on 2026-05-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_espejomemoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictsession',
            name='pregunta_cierre',
            field=models.TextField(blank=True),
        ),
    ]
