# Generated by Django 6.0.4 on 2026-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometrics', '0003_add_likert5a_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='instrument_type',
            field=models.CharField(choices=[('clinical', 'Instrumento Validado'), ('adapted', 'Adaptación de Instrumento Validado'), ('custom', 'Herramienta de Autoconocimiento')], default='custom', max_length=20),
        ),
    ]
