# Generated by Django 6.0.4 on 2026-05-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundtemplate',
            name='preview_url',
        ),
    ]
