# Generated by Django 6.0.5 on 2026-05-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ebook', 'Endonautica (ebook)'), ('marco_teorico', 'Marco Teórico'), ('tradicion', 'Tradición / Sistema')], max_length=20)),
                ('autor_ref', models.CharField(blank=True, max_length=150)),
                ('procesado', models.BooleanField(default=False)),
                ('n_chunks', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento Mirror KB',
                'verbose_name_plural': 'Documentos Mirror KB',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MirrorChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_index=True, max_length=20)),
                ('contenido', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='mirror.mirrordocumento')),
            ],
            options={
                'verbose_name': 'Chunk Mirror KB',
                'ordering': ['documento', 'chunk_index'],
            },
        ),
    ]
