# Generated by Django 6.0.4 on 2026-05-15 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_mirror_kb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspejoMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('contenido', models.TextField()),
                ('activa', models.BooleanField(default=False)),
                ('fuente', models.CharField(choices=[('inicial', 'Estado inicial'), ('sesion', 'Generada desde sesión'), ('restauracion', 'Restaurada por usuario')], default='sesion', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorias_generadas', to='mirror.conflictsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espejo_memorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memoria del Espejo',
                'ordering': ['-version'],
                'unique_together': {('user', 'version')},
            },
        ),
    ]
