# Generated by Django 6.0.4 on 2026-05-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_espejomemoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictsession',
            name='tokens_used',
        ),
        migrations.AlterField(
            model_name='espejomemoria',
            name='fuente',
            field=models.CharField(choices=[('perfil', 'Generada desde perfil'), ('sesion', 'Generada desde sesión'), ('restauracion', 'Restaurada por usuario')], default='sesion', max_length=20),
        ),
    ]
