# Generated by Django 6.0.4 on 2026-05-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
