# Generated by Django 6.0.4 on 2026-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0002_add_gender_to_birthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthreport',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
