# Generated by Django 6.0.4 on 2026-05-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_hotmart_subscriber_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens_last_renewed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
