# Generated by Django 6.0.4 on 2026-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_tokens_last_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='map_aesthetic',
            field=models.CharField(blank=True, choices=[('cosmos', 'Cosmos'), ('mandala', 'Mandala'), ('archipielago', 'Archipiélago'), ('arbol', 'Árbol')], default='', max_length=20),
        ),
    ]
