# Generated by Django 6.0.4 on 2026-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_map_aesthetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_entry_point',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_noise_area',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_prior_exploration',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_question',
            field=models.TextField(blank=True),
        ),
    ]
