# Generated by Django 6.0.4 on 2026-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_onboarding_entry_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_nucleo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
