# Generated by Django 6.0.4 on 2026-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_onboarding_nucleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='map_aesthetic',
            field=models.CharField(blank=True, choices=[('cosmos', 'Cósmico'), ('mandala', 'Mandala'), ('archipielago', 'Archipiélago'), ('arbol', 'Árbol')], default='', max_length=20),
        ),
    ]
