# Generated by Django 6.0.4 on 2026-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_map_aesthetic_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='map_aesthetic',
            field=models.CharField(blank=True, choices=[('cosmos', 'Cósmico'), ('mandala', 'Geometría Sagrada'), ('psychedelic', 'Psicodélico'), ('archipielago', 'Archipiélago'), ('arbol', 'Árbol')], default='', max_length=20),
        ),
    ]
