# Generated by Django 6.0.4 on 2026-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_psychedelic_aesthetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_public',
            field=models.BooleanField(default=False),
        ),
    ]
