# Generated by Django 6.0.4 on 2026-05-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_active_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='map_aesthetic',
            field=models.CharField(blank=True, choices=[('cosmos', 'Cósmico'), ('mandala', 'Geometría Sagrada'), ('psychedelic', 'Psicodélico')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('navegante', 'Navegante — $10/mes'), ('practicante', 'Facilitador — $39/mes'), ('empresa', 'Empresa')], default='free', max_length=20),
        ),
    ]
