# Generated by Django 6.0.4 on 2026-05-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='map_aesthetic',
            field=models.CharField(blank=True, choices=[('cosmos', 'Cósmico'), ('psychedelic', 'Psicodélico'), ('estrellas', 'Estrellas'), ('mandala', 'Geometría Sagrada')], default='', max_length=20),
        ),
    ]
