# Generated by Django 6.0.5 on 2026-06-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_active_template_add_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('navegante', 'Navegante — $10/mes'), ('practicante', 'Facilitador — $39/mes'), ('empresa', 'Empresa')], default='free', max_length=20),
        ),
    ]
