# Generated by Django 6.0.5 on 2026-06-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='etapa',
            field=models.CharField(choices=[('0', 'Pre-Lanzamiento'), ('1', 'Lanzamiento y Captación'), ('2', 'Análisis e Iteración'), ('backlog', 'Backlog / Futuro')], default='0', max_length=20),
        ),
    ]
