# Generated by Django 6.0.4 on 2026-05-26 22:34

import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Índice del Blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de publicación')),
                ('intro', models.CharField(blank=True, max_length=280)),
                ('body', wagtail.fields.StreamField([('richtext', 0), ('imagen', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'})})),
                ('cta_text', models.CharField(blank=True, max_length=80, verbose_name='Texto del CTA')),
                ('cta_url', models.URLField(blank=True, verbose_name='URL del CTA')),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('is_community', models.BooleanField(default=False, verbose_name='Publicado por la comunidad')),
            ],
            options={
                'verbose_name': 'Artículo del Blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='BlogSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email del autor')),
                ('author_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre del autor')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Texto')),
                ('source_type', models.CharField(choices=[('espejo', 'Sesión del Espejo'), ('test', 'Resultado de Test'), ('birth', 'Lectura de Nacimiento'), ('free', 'Texto libre')], default='free', max_length=10)),
                ('source_description', models.TextField(blank=True, verbose_name='Descripción del origen')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='submitted', max_length=12)),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='Notas del revisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Postulación al Blog',
                'verbose_name_plural': 'Postulaciones al Blog',
                'ordering': ['-updated_at'],
            },
        ),
    ]
