# Generated by Django 6.0.5 on 2026-06-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_body_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedarticle',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='blog_post',
            field=models.ForeignKey(blank=True, help_text='Artículo de Wagtail (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='carrusel_hashtags',
            field=models.TextField(blank=True, help_text='Hashtags para Instagram (ej: #autoconocimiento #psicología)', verbose_name='Hashtags carrusel'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='copy_instagram',
            field=models.TextField(blank=True, help_text='Texto completo formateado para Instagram (gancho + cuerpo + CTA + hashtags)', verbose_name='Copy Instagram'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='generated_article',
            field=models.ForeignKey(blank=True, help_text='Artículo generado por IA (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='blog.generatedarticle'),
        ),
    ]
