# Generated by Django 6.0.4 on 2026-05-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryprofile',
            name='token_allocation',
        ),
        migrations.RemoveField(
            model_name='temporaryprofile',
            name='tokens_used',
        ),
    ]
