# Generated by Django 6.0.5 on 2026-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0002_cleanup_unused_fields'),
        ('psychometrics', '0005_remove_token_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryprofile',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, related_name='assigned_profiles', to='psychometrics.test'),
        ),
        migrations.AddField(
            model_name='temporaryprofile',
            name='clinical_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='temporaryprofile',
            name='clinical_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
