# Generated by Django 6.0.5 on 2026-06-13 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Error')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='soul_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soul_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
