# Generated by Django 6.0.5 on 2026-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulreport',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
