# Generated by Django 6.0.4 on 2026-05-26 22:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('cta_app_text', models.CharField(default='Comenzar el viaje', max_length=80)),
                ('cta_app_url', models.URLField(default='https://app.endonautas.cl')),
                ('cta_ebook_text', models.CharField(default='Descargar Endonautica', max_length=80)),
                ('cta_ebook_url', models.URLField(default='https://ebook.endonautas.cl')),
            ],
            options={
                'verbose_name': 'Página de Inicio',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Página Simple',
            },
            bases=('wagtailcore.page',),
        ),
    ]
