# Generated by Django 6.0.4 on 2026-05-29 01:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndonauticaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Titular')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introducción')),
                ('hotmart_url', models.URLField(blank=True, verbose_name='URL de compra (Hotmart)')),
                ('hotmart_cta', models.CharField(default='Conseguir el libro', max_length=80, verbose_name='Texto del CTA')),
                ('features', wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Símbolo Unicode, ej: ◇ ◈ ✦', 'max_length': 10}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}, verbose_name='Características')),
                ('excerpt', models.TextField(blank=True, verbose_name='Extracto del libro')),
            ],
            options={
                'verbose_name': 'Página Endonautica (libro)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EquipoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Intro filosófica')),
                ('bio', wagtail.fields.RichTextField(blank=True, verbose_name='Biografía de Franco')),
                ('photo_url', models.URLField(blank=True, default='https://ebook.endonautas.cl/assets/img/franco-jeria.jpeg', verbose_name='URL foto')),
            ],
            options={
                'verbose_name': 'Página Equipo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MascaraPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Titular')),
                ('subheadline', models.CharField(blank=True, max_length=300, verbose_name='Subtitular')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción del lead magnet')),
                ('brevo_list_id', models.PositiveIntegerField(default=3, verbose_name='ID de lista Brevo')),
                ('hotmart_url', models.URLField(blank=True, verbose_name='URL Hotmart (upsell post-suscripción)')),
                ('thank_you_text', models.TextField(blank=True, default='¡Listo! Te enviamos el PDF a tu correo.', verbose_name='Mensaje de confirmación')),
            ],
            options={
                'verbose_name': 'Página MÁSCARA (lead magnet)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
