# Generated by Django 6.0.4 on 2026-06-02 18:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_endonauticapage_equipopage_mascarapage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HacksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subheadline', models.CharField(blank=True, max_length=300, verbose_name='Subtitular')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('brevo_list_id', models.PositiveIntegerField(default=5, verbose_name='ID de lista Brevo')),
                ('thank_you_text', models.TextField(blank=True, default='¡Listo! Revisa tu correo. No la leas de corrido — lee un hack, desaparece un día, vuelve al siguiente.', verbose_name='Mensaje de confirmación')),
            ],
            options={
                'verbose_name': 'Página Hacks (3 Hacks de Endonáutica)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ViajePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subheadline', models.CharField(blank=True, max_length=300, verbose_name='Subtitular')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('brevo_list_id', models.PositiveIntegerField(default=6, verbose_name='ID de lista Brevo')),
                ('thank_you_text', models.TextField(blank=True, default='¡Listo! Revisa tu correo. El viaje no tiene deadline — pero hoy es un buen día para arrancar.', verbose_name='Mensaje de confirmación')),
            ],
            options={
                'verbose_name': 'Página Viaje (Guía Viaje Interior)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
