# Generated by Django 6.0.5 on 2026-06-14 13:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_mascarapage_brevo_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='hackspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='mascarapage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='viajepage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='homepage',
            name='lead_magnets',
            field=wagtail.fields.StreamField([('lead_magnet', 5)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('mascara', 'Test de Máscaras'), ('hacks', '3 Hacks de Endonáutica'), ('viaje', 'Viaje Interior'), ('endonautica', 'Libro Endonáutica')], 'label': 'Tipo de Magnet'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titular/Frase principal', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Acceder →', 'label': 'Texto del botón', 'required': True}), 3: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Para magnets gratuitos', 'label': 'ID Lista Brevo', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Para magnets de pago', 'label': 'URL Hotmart', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('magnet_type', 0), ('headline', 1), ('cta_text', 2), ('brevo_list_id', 3), ('hotmart_url', 4)]], {})}, verbose_name='Bento Grid de Magnets'),
        ),
        migrations.DeleteModel(
            name='EndonauticaPage',
        ),
        migrations.DeleteModel(
            name='EquipoPage',
        ),
        migrations.DeleteModel(
            name='HacksPage',
        ),
        migrations.DeleteModel(
            name='MascaraPage',
        ),
        migrations.DeleteModel(
            name='ViajePage',
        ),
    ]
