# Generated by Django 6.0.5 on 2026-05-12 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('dimension', models.CharField(choices=[('identidad', 'Identidad y Personalidad'), ('emociones', 'Emociones y Regulación'), ('cuerpo', 'Cuerpo y Sensorialidad'), ('mente', 'Mente y Aprendizaje'), ('vinculos', 'Vínculos y Apego'), ('sombra', 'Sombra y Patrones'), ('espiritualidad', 'Espiritualidad y Sentido'), ('suenos', 'Sueños y Conciencia'), ('proposito', 'Propósito y Trabajo'), ('comunidad', 'Comunidad y Relaciones'), ('abundancia', 'Abundancia y Finanzas'), ('creatividad', 'Creatividad e Integración')], max_length=30)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('estimated_minutes', models.IntegerField(default=5)),
                ('token_cost', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['dimension', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dimension_key', models.CharField(blank=True, max_length=80)),
                ('scale', models.CharField(choices=[('likert5', 'Likert 1-5'), ('likert4', 'Likert 0-4'), ('likert7', 'Likert 1-7'), ('binary', 'Sí / No')], default='likert5', max_length=10)),
                ('reverse_scored', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psychometrics.test')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField(default=dict)),
                ('evaluation', models.JSONField(default=dict)),
                ('ai_insight', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('temp_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='practitioners.temporaryprofile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='psychometrics.test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
