# Generated by Django 6.0.5 on 2026-05-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scale',
            field=models.CharField(choices=[('likert5', 'Likert 1-5'), ('likert4', 'Likert 0-4'), ('likert3', 'Likert 0-3'), ('likert7', 'Likert 1-7'), ('binary', 'Sí / No')], default='likert5', max_length=10),
        ),
    ]
