# Generated by Django 6.0.4 on 2026-05-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometrics', '0002_add_likert3_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scale',
            field=models.CharField(choices=[('likert5', 'Likert 1-5 (frecuencia)'), ('likert5a', 'Likert 1-5 (acuerdo)'), ('likert4', 'Likert 0-4'), ('likert3', 'Likert 0-3'), ('likert7', 'Likert 1-7'), ('binary', 'Sí / No')], default='likert5', max_length=10),
        ),
    ]
