# Generated by Django 6.0.4 on 2026-05-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychometrics', '0004_add_instrument_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='token_cost',
        ),
    ]
