# Generated by Django 6.0.5 on 2026-06-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_fix_emailevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailevent',
            new_name='crm_emailev_subscri_33e009_idx',
            old_name='emailevent_sub_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='emailevent',
            new_name='crm_emailev_event_t_411576_idx',
            old_name='emailevent_evt_occ_idx',
        ),
    ]
