# Generated by Django 6.0.4 on 2026-05-16 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('fracton_reward', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Misión',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='tokenbalance',
            options={'verbose_name': 'Balance de Fractones'},
        ),
        migrations.AlterModelOptions(
            name='tokentransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transacción de Fractones'},
        ),
        migrations.RenameField(
            model_name='tokenbalance',
            old_name='balance',
            new_name='monthly',
        ),
        migrations.RemoveField(
            model_name='tokenpack',
            name='tokens',
        ),
        migrations.AddField(
            model_name='tokenbalance',
            name='monthly_last_renewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenbalance',
            name='permanent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenpack',
            name='fractones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='source',
            field=models.CharField(choices=[('permanent', 'Permanente'), ('monthly', 'Mensual'), ('spend', 'Gasto')], default='permanent', max_length=20),
        ),
        migrations.CreateModel(
            name='MissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tokens.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Misión completada',
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
