# Generated by Django 6.0.4 on 2026-05-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_fractones_and_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='prerequisite_slug',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
