# Generated by Django 6.0.4 on 2026-06-04 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_add_mission_prerequisite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenpack',
            options={'ordering': ['order'], 'verbose_name': 'Pack de Fractones'},
        ),
        migrations.RemoveField(
            model_name='tokenpack',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='tokenpack',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenpack',
            name='price_clp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenpack',
            name='slug',
            field=models.CharField(default='pack', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='source',
            field=models.CharField(choices=[('permanent', 'Permanente'), ('monthly', 'Mensual'), ('spend', 'Gasto'), ('mp_pack', 'Pack MP')], default='permanent', max_length=20),
        ),
        migrations.CreateModel(
            name='MpPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100)),
                ('pack_slug', models.CharField(blank=True, max_length=30)),
                ('fractones', models.IntegerField(default=0)),
                ('amount_clp', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('refunded', 'Reembolsada')], default='pending', max_length=20)),
                ('mp_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.tokenpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra Mercado Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
