# Generated by Django 6.0.4 on 2026-06-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_tokenpack_options_remove_tokenpack_price_usd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpack',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='source',
            field=models.CharField(choices=[('permanent', 'Permanente'), ('monthly', 'Mensual'), ('spend', 'Gasto'), ('mp_pack', 'Pack MP'), ('pp_pack', 'Pack PayPal')], default='permanent', max_length=20),
        ),
        migrations.CreateModel(
            name='PayPalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_order_id', models.CharField(blank=True, max_length=100)),
                ('pp_payer_id', models.CharField(blank=True, max_length=100)),
                ('pack_slug', models.CharField(blank=True, max_length=30)),
                ('fractones', models.IntegerField(default=0)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('refunded', 'Reembolsada')], default='pending', max_length=20)),
                ('pp_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.tokenpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra PayPal',
                'ordering': ['-created_at'],
            },
        ),
    ]
